version: "2"
#
# Docker-compose file for
# the gitlab DFST container.
#
services:
  gitlab-dfst:
    hostname: ${HOSTNAME}
    ports: 
     - "80:80"
     - "443:443"
     - "8022:22"
    container_name: gitlab-dfst
     
    image: dfst/gitlab-dfst
#
# End of compose file.
#  