version: "2"

#
# DITA For Small Teams (DFST) Docker compose
# run configuration file. Will run all the 
# containers with appropriate default settings. 
#
# FIXME: Parameterize all appropriate options
#        with variables with defaults (defined
#        in the relevant docker files).
#
# It runs the DITA OT container, the gitlab 
# server (for shared git access and continuous
# integration), and the DFST Link Manager application.
#
# Gitlab is exposed on the default ports 80 and 443
# for HTTP/HTTPS access and 8022 for SSH
#
# The Link Manager is exposed on the default ports
# of 8984 for the Web app and 1984 for the underlying
# BaseX server (used by the git hooks installed in the
# GitLab repositories).
#
# The Web server is exposed on port 8080.
# 
# Placeholder for now, will add appropriate
# variables later (e.g., ports for Web services,
# host-side mount points).

services:
#
# DITA OT
#
# This container provides access to a DITA Open Toolkit
# instace. GitLab uses it to run the OT, BaseX uses
# it for access to DTDs. 
#
  dita-ot:
    extends:
       file: dita-ot/docker-compose.yml  
       service: dita-ot-dfst
    volumes_from:
       - web-delivery
 
#
# DFST Link Manager
#
# The Link Manager provides link-related information
# for use by authors via an interactive Web app
# or other applications via REST API.
#
# It gets files from the git server and depends on
# the DITA Open Toolkit to resolve references to 
# DTDs or other grammar files.
#  
  linkmgr-webapp:
     extends:
       file: link-manager-webapp/docker-compose.yml
       service: linkmgr-basex-webapp
     container_name: linkmgr-webapp
     
  linkmgr:

    extends:
      file: link-manager-basex/docker-compose.yml
      service: linkmgr-basex

    volumes:
       - /Users:/Users
# Uncomment and adjust these lines in order to have the Link Manager
# use a local copy of the Web app source for development purposes:       
       - /Users/ekimber/workspace-dfst/dfst-linkmgmt-basex/webapp:/webapp
       - /Users/ekimber/workspace-dfst/dfst-linkmgmt-basex/modules:/repo
  
    volumes_from:
     - dita-ot
 
#
# GitLab

#
# Copied from https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml
#
# Runs the required postgresql and redis servers:
#
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-12
    container_name: postgresql
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
    volumes:
      - /tmp/docker/gitlab/postgresql:/var/lib/postgresql
    
  redis:
    restart: always
    image: sameersbn/redis:latest
    container_name: redis
    volumes:
      - /tmp/docker/gitlab/redis:/var/lib/redis      

#
# The GitLab server provides two services:
#
# - Shared git access
# - Continuous integration for automating 
#   builds (e.g., HTML and PDF generation)
#   
  gitlab:
  
    extends:
       file: gitlab-dfst/docker-compose.yml
       service: gitlab-dfst
    hostname: ${HOSTNAME}
    environment:
      - GITLAB_SECRETS_DB_KEY_BASE=8WgpQbrcNZtXPzzGL3cgsdL234HmpRsfqWsKJLtqwJJk2VkQS2FFVBwssV3xcnWt
      
    volumes:
      - /tmp/gitlab/git-data:/var/opt/gitlab/git-data
    volumes_from:
      - dita-ot
      - linkmgr
      
#
# Define the GitLab runner
# that will be used to run build jobs;
#      
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/gitlab-runner/config:/etc/gitlab-runner

#
# Web server for HTML delivery
#

  web-delivery:
    extends:
       file: caddy-dfst/docker-compose.yml  
       service: caddy-dfst
    volumes:
      - /Users/ekimber/temp/webdelivery:/srv/www
      
#
# Demo content data volume:
#
# Using top as the command so the container is always running
# so we can then copy files out of it (which requires a running
# container).
#
# Defines volume /opt/dita-community/data/Thunderbird
#
  demo-content:
    image: ditacommunity/demo-content
    container_name: demo-content
    command: top
      
#  
# End of compose file.
#
