version: "2"
#
# Docker-compose file for
# the D4ST Caddy Web server used to deliver
# generated deliverables (HTML, PDF, EPUB, etc.)
# 
# See e.g., https://hub.docker.com/r/abiosoft/caddy/
# 
services:
  caddy-d4st:
    # hostname: ${HOSTNAME}
    ports: 
      - "${WEBDELIVERY_PORT}:2015"
    container_name: caddy-d4st
    volumes: ["/srv/www"] 
     
    image: d4st/caddy-d4st
#
# End of compose file.
#  