version: "2"

#
# DITA For Small Teams (DFST) Docker compose
# run configuration file. Will run all the 
# containers with appropriate default settings. 
#
# FIXME: Parameterize all appropriate options
#        with variables with defaults (defined
#        in the relevant docker files).
#
# It runs the DITA OT container, the gitlab 
# server (for shared git access and continuous
# integration), and the DFST Link Manager application.
#
# Gitlab is exposed on the default ports 80 and 443
# for HTTP/HTTPS access and 8022 for SSH
#
# The Link Manager is exposed on the default ports
# of 8984 for the Web app and 1984 for the underlying
# BaseX server (used by the git hooks installed in the
# GitLab repositories).
# 
# Placeholder for now, will add appropriate
# variables later (e.g., ports for Web services,
# host-side mount points).


services:
#
# DITA OT
#
# This container provides access to a DITA Open Toolkit
# instace. GitLab uses it to run the OT, BaseX uses
# it for access to DTDs. 
#
  dita-ot:
    extends:
       file: ../../containers/dita-ot/docker-compose.yml  
       service: dita-ot-dfst
 
#
# DFST Link Manager
#
# The Link Manager provides link-related information
# for use by authors via an interactive Web app
# or other applications via REST API.
#
# It gets files from the git server and depends on
# the DITA Open Toolkit to resolve references to 
# DTDs or other grammar files.
#  
  linkmgr:

    extends:
      file: ../../containers/link-manager-basex/docker-compose.yml
      service: linkmgr-basex

    volumes:
       - /Users:/Users
  
    volumes_from:
     - dita-ot
 
#
# GitLab
#
# The GitLab server provides two services:
#
# - Shared git access
# - Continuous integration for automating 
#   builds (e.g., HTML and PDF generation)
#   
  gitlab:
  
    extends:
       file: ../../containers/gitlab-dfst/docker-compose.yml
       service: gitlab-dfst
    hostname: ${HOSTNAME}
    volumes_from:
      - dita-ot
      - linkmgr
#  
# End of compose file.
#
